### ISSUE TITLE
Unable to verify a token using ES256 signature encoding

### ISSUE THREAD

**Issue by drupol** [web-token/jwt-framework#301]
Hello,

I'm trying to decode and verify a token signed using `ES256` algorithm.

So far I tried many ways and I'm not able to do such a simple thing. I also checked the documentation, but I'm confused in between `JWSVerifier` and `JWTVerifier`. Which one to use, and how to use properly in my use case?

I quickly made a [gist](https://gist.github.com/drupol/0123d027b5151550b719ac44f50cec86) containing the code that I'm using, including the token I'm trying to decode.

When I run this example, it says:

```
PHP Fatal error:  Uncaught InvalidArgumentException: The algorithm "ES256" is not supported. in vendor/web-token/jwt-core/AlgorithmManager.php:66
Stack trace:
#0 vendor/web-token/jwt-signature/JWSVerifier.php(158): Jose\Component\Core\AlgorithmManager->get()
#1 vendor/web-token/jwt-signature/JWSVerifier.php(94): Jose\Component\Signature\JWSVerifier->getAlgorithm()
#2 vendor/web-token/jwt-signature/JWSVerifier.php(88): Jose\Component\Signature\JWSVerifier->verifySignature()
#3 vendor/facile-it/php-jose-verifier/src/Validate/Validate.php(35): Jose\Component\Signature\JWSVerifier->verifyWithKeySet()
#4 vendor/facile-it/php-jose-verifier/src/JWTVerifier.php(23): Facile\JoseVerifier\Validate\Validate->run()
#5 vendor/facile-it/php-jose-verifier/src/AbstractTokenVerifier.php on line 315
```

Could you please advise me on how to fix this? Or point to some documentation?

**Comment by drupol** [comment]
Ok, I was missing the package `web-token/jwt-signature-algorithm-ecdsa`.

**Comment by Spomky** [comment]
Hi @drupol,

Sorry for the late-and-now-useless-answer. Past days, I was focused on burning servers and datacenters and data replication.

`JWSVerifier` is dedicated to JWS, while `JWTVerifier` ... it looks like it is not part of this framework.
Hereafter a commented example:

```php
<?php

use Jose\Component\Checker\ClaimCheckerManager;
use Jose\Component\Checker\HeaderCheckerManager;
use Jose\Component\Core\AlgorithmManager;
use Jose\Component\KeyManagement\JKUFactory;
use Jose\Component\Signature\Algorithm\ES256;
use Jose\Component\Signature\JWSTokenSupport;
use Jose\Component\Signature\JWSVerifier;
use Jose\Component\Signature\Serializer\CompactSerializer;

require_once 'vendor/autoload.php';

$token = 'eyJhbGciOiAiRVMyNTYiLCAiY3R5IjoiSldUIn0.eyJhdCI6IkFULTU2MTIwODgtbGhXbzYwQUJkd25raVpnTGZCaFA5ZDFpTXJCVWl2NjFMOGxVV3pHN3ptUWFLSG81Z0FqNXRNT3B6cnAzOG15ZVk4U290enNVdG1jbDV4OUpGelVXVVB0LXJhOGduQ0YxbFdhbGw3WVQyR0VCQUstcVZMUlJ5RzMyRjJaS2VxY21DYXJRazI5Qk00VnRJdzBtU2RXUldjelhPZnhrY3FLeTRUcU1oalJHcGJ0UEJma3p6UXVSblEwWmt6dENlNGdhaHlPallTIiwidHMiOjE2MTUzODc3MTk2OTN9.QZE4mWYNvf9CAAF8sX5TylmUL3X88qqHHavlHOy4J-_XjUgtLV6jwTC7H-PYc__sYznTbo5LpsOoUZHYgdZKlw';

// To convert a token into a JWS object
$serializer = new CompactSerializer();
$jws = $serializer->unserialize($token);

// The algorithms we want to use
$algorithmManager = new AlgorithmManager([
    new ES256(),
]);

// The JWKSet (public keys provided from a URL)
$jwkuFactory = new JKUFactory($psrClient, $requestFactory);
$jwkset = $jwkuFactory->loadFromUrl('https://vvvvv');

// We check the token signature
$verifier = new JWSVerifier($algorithmManager);
$isValid = $verifier->verifyWithKeySet($jws, $jwkset, 0); // 0 means the first signature from the token (tokens may have several signatures)
if (!$isValid) {
    die('Invalid signature');
}

//The signature is correct, we can get the payload and check the claims and header parameters
$payload = $jws->getPayload();
$claims = json_decode($payload, true);

$claimChecker = new ClaimCheckerManager(
    [/*Depends on the content of your token, context, application needs*/]
);
$claimChecker->check($claims, [/*if there are mandatory claims, they should be checked and listed here*/]);

$headerChecker = new HeaderCheckerManager(
    [/*Depends on the content of your token, context, application needs*/],
    [new JWSTokenSupport()] // The header checker manager can be used for both JWS and JWE. We just need JWS support in this use case
);
$headerChecker->check($jws, 0); // 0 means the first signature from the token (tokens may have several signatures)

//At this stage, we have a valed token with verified headers and claims.
//Claims can safely be used by the application
```

**Comment by drupol** [comment]
Thank you very much, editing my previous message and remove my sarcasm !

Good luck with your work!
